version: '3.8'

services: 
  mysqldb:
    image: mysql:8.0.30
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=applicants2023
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password  
      - MYSQL_HOSTNAME=mysqldb
      - JWT_SECRET=mySecretKey123
      - COOKIE_SECRET=mysecretcookiekey
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin@123
      - userFilePath=files
    ports:
      - 3306:3306
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -ppassword || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  backend:
    build: ./BTP_Backend
    image: btp-backend-compose
    environment:
      - MYSQL_DATABASE=applicants2023
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOSTNAME=mysqldb
      - MYSQL_HOST_IP=mysqldb
      - JWT_SECRET=mySecretKey123
      - COOKIE_SECRET=mysecretcookiekey
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin@123
      - userFilePath=files
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 4444:4444
    volumes: 
      - ./backend-files:/usr/src/app/files
    stdin_open: true
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4444/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./BTP_Frontend
    image: btp-frontend-compose
    ports:
      - 80:8004
    stdin_open: true
    restart: always

volumes: 
  db-config:
  db-data:
