version: '3.8'

services:
  #Database with two volumes  
  mysqldb_CSE:
    image: mysql:8.0.30
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=Applicants2023_CSE
      - MYSQL_PASSWORD=Your_Password
      - MYSQL_ROOT_PASSWORD=Your_Password
      - MYSQL_HOSTNAME=mysqldb_CSE
    ports:
      - 5545:3306
    volumes: 
      - db-config-CSE:/etc/mysql
      - db-data:-CSE/var/lib/mysql
  
  #Backend with one volume to store files folder  
  backend_CSE:
    build: ./BTP_Backend
    image: btp-backend-compose
    environment:
      - MYSQL_DATABASE=Applicants2023_CSE
      # Note that the MYSQL_PASSWORD should be same as MYSQL_ROOT_PASSWORD here
      - MYSQL_PASSWORD=Your_Password
      - MYSQL_ROOT_PASSWORD=Your_Password
      - MYSQL_HOSTNAME=mysqldb_CSE
    depends_on:
      - mysqldb_CSE
    ports:
      - 4444:4444
    volumes: 
      - ./backend-CSE-files:/usr/src/app/files
      - ./backend-CSE-files/generatedOffers:/usr/src/app/files/generatedOffers
      - ./backend-CSE-files/roundUpdates:/usr/src/app/files/roundUpdates
    stdin_open: true
    tty: true
    restart: on-failure
  
  #Frontend 
  frontend_CSE:
    build: ./BTP_Frontend
    image: btp-frontend-compose
    ports:
      - 3000:8004
    stdin_open: true

volumes: 
  db-config-CSE:
  db-data-CSE:





